name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to Tail UI. Kudos on the first issue.'' first issue'
        pr-message: 'Welcome to Tail UI. Kudos on the first PR. Thanks for taking time. The PR is in review. Happy Coding! '' first pr'
